rules:
- id: 1
  'on':
  - Dot11AssoReq
  - Dot11AssoResp
  - Dot11ReassoReq
  - Dot11ReassoResp
  - Dot11Auth
  - EAPOL
  class: impersonation
  type: alert
  msg: client communicating with fake/spoofed network
  cooldown: 0s
  indicators:
  - id: client attempting to associate to fake network
    'on':
    - Dot11AssoReq
    - Dot11ReassoReq
    cooldown: 1s
    attrs:
      - layer: Dot11
        attr: addr1
        value: "$home"
        operation: "=="
        on_missing: ignore
      - layer: RadioTap
        attr: channel
        value: "$home"
        operation: "!in"
        on_missing: ignore
  - id: client associated to fake network
    'on':
    - Dot11AssoResp
    - Dot11ReassoResp
    cooldown: 1s
    attrs:
      - layer: Dot11
        attr: addr2
        value: "$home"
        operation: "=="
        on_missing: ignore
      - layer: RadioTap
        attr: channel
        value: "$home"
        operation: "!in"
        on_missing: ignore
  - id: authentication to fake network
    'on':
    - Dot11Auth
    cooldown: 1s
    attrs:
      - layer: Dot11
        attr: addr1
        value: "$home"
        operation: "=="
        on_missing: ignore
      - layer: RadioTap
        attr: channel
        value: "$home"
        operation: "!in"
        on_missing: ignore
  - id: 4-Way handshake with fake network
    'on':
      - EAPOL
    cooldown: 0s
    attrs:
      - layer: Dot11
        attr: addr1
        value: "$home"
        operation: "=="
        on_missing: ignore
      - layer: RadioTap
        attr: channel
        value: "$home"
        operation: "!in"
        on_missing: ignore

- id: 2
  'on':
  - Dot11Deauth
  class: dos
  type: alert
  cooldown: 10s
  msg: Dot11Deauthentication attack
  indicators:
  - id: fluctuating rssi
    'on':
    - Dot11Deauth
    cooldown: 1s
    attrs:
      - layer: RadioTap
        attr: dBm_AntSignal
        value: "$!home"
        operation: "!="
        fluctiation: 5
        on_missing: ignore
      - layer: Dot11
        attr: addr2
        value: "$home"
        operation: "=="
        on_missing: ignore
  - id: non-ap source, broadcast dst
    'on':
    - Dot11Deauth
    cooldown: 1s
    attrs:
      - layer: Dot11
        attr: addr2
        operation: "!="
        value: "$home"
        on_missing: ignore
      - layer: Dot11
        attr: addr1
        value: "ff:ff:ff:ff:ff:ff"
        operation: "=="
        on_missing: ignore
  - id: broadcast Dot11Deauthentication
    'on':
    - Dot11Deauth
    cooldown: 1s
    attrs:
      - layer: Dot11
        attr: addr1
        operation: "=="
        value: ff:ff:ff:ff:ff:ff
        on_missing: ignore
  - id: reason code 7 - aircrack
    'on':
    - Dot11Deauth
    cooldown: 1s
    attrs:
      - layer: Dot11Deauth
        attr: reason_code
        operation: "=="
        value: 7
        on_missing: ignore
        
